//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RugFactory.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albaran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Albaran()
        {
            this.Is_Confirmado = false;
            this.Is_Trabajo_Terminado = false;
            this.Alfombras = new HashSet<Alfombra>();
            this.Lavados = new HashSet<Lavado>();
        }
    
        public int Albaran_Id { get; set; }
        public string Recogido_Por { get; set; }
        public Nullable<System.DateTime> Fecha_Entrada { get; set; }
        public string Foto_Job { get; set; }
        public Nullable<System.DateTime> Fecha_BaseDatos { get; set; }
        public string Presupuesto { get; set; }
        public bool Is_Confirmado { get; set; }
        public bool Is_Trabajo_Terminado { get; set; }
        public int ClienteCliente_Id { get; set; }
        public string Parte_Confirmado { get; set; }
        public Nullable<short> Total_Items_Quantity { get; set; }
        public string Numero_Albaran { get; set; }
        public bool Is_Active { get; set; }
        public string NumeroDeAviso { get; set; }
        public Nullable<System.DateTime> fecha_Estimada { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Factura Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alfombra> Alfombras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lavado> Lavados { get; set; }
    }
}
