//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RugFactory.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Is_Cobrado = false;
            this.Is_Entregado = "False";
            this.Descuento = 0;
            this.Alfombras = new HashSet<Alfombra>();
        }
    
        public int Fatura_Id { get; set; }
        public short Total { get; set; }
        public bool Is_Cobrado { get; set; }
        public string Metodo_Pago { get; set; }
        public System.DateTime Fecha_Emicion { get; set; }
        public System.DateTime Fecha_Entrega { get; set; }
        public int ClienteCliente_Id { get; set; }
        public string Entregado_Por { get; set; }
        public int ContactContact_Id { get; set; }
        public string Is_Entregado { get; set; }
        public short Descuento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Albaran Albaran { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alfombra> Alfombras { get; set; }
    }
}
