//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RugFactory.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class FalloAlfombra
    {
        public int FalloId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    }
}
