//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RugFactory.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RugDataBase_Context : DbContext
    {
        public RugDataBase_Context()
            : base("name=RugDataBase_Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Alfombra> Alfombras { get; set; }
        public virtual DbSet<FalloAlfombra> FallosAlfombra { get; set; }
        public virtual DbSet<Albaran> Albaranes { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Lavado> Lavados { get; set; }
    }
}
